services:
  dind:
    container_name: netpart-dind
    build: "./dind"
    privileged: true
    environment:
      - DOCKER_HOST=unix:///mnt/docker.sock
      - POSTGRES_IMAGE=postgres:16.3-alpine3.20
    volumes:
      - dockersock:/mnt/
      - ./dind/images/:/images
    networks:
      - control-plane
    healthcheck:
      test: ["CMD-SHELL", "docker", "version"]
      interval: 3s
      timeout: 3s
      retries: 5
  control:
    container_name: netpart-control
    build: "./server"
    environment:
      - DOCKER_HOST=unix:///mnt/docker.sock
      - POSTGRES_IMAGE=postgres:16.3-alpine3.20
    volumes:
      - dockersock:/mnt/
      - ./server/src/:/app
    networks:
      - control-plane
    depends_on:
      dind:
        condition: "service_healthy"

volumes:
  dockersock:

networks:
  control-plane:
