services:
  dind:
    image: docker:28.0.0-rc.3-dind-alpine3.21
    container_name: dind
    privileged: true
    environment:
      - DOCKER_HOST=unix:///mnt/docker.sock
    volumes:
      - ./sock/:/mnt/
    healthcheck:
      test: ["CMD-SHELL", "docker", "version"]
      interval: 3s
      timeout: 3s
      retries: 5
